run-name: ${{ github.actor }} is creating Lua Love game files 🚀
on: [push]   
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Build the applications
    - uses: nhartland/love-build@master
      with:
       app_name: 'snake'
       love_version: '11.4'
    # Upload the built applications
    - uses: actions/upload-artifact@v1
      with:
        name: built-applications
        path: 'release'
